/*
 * ultrasonic_sensor.h
 *
 *  Created on: Oct 2, 2025
 *      Author: Abdullah Said
 */

#ifndef ULTRASONIC_SENSOR_H_
#define ULTRASONIC_SENSOR_H_
#include "std_types.h"

/*trigger and echo pins and ports id for configurations
 * */
#define ULTRASONIC_TRIGGER_PORT_ID  PORTD_ID
#define ULTRASONIC_TRIGGER_PIN_ID	PIN7_ID

#define ULTRASONIC_ECHO_PORT_ID  PORTD_ID
#define ULTRASONIC_ECHO_PIN_ID	PIN6_ID

/*description:
 *  Initialize the ICU driver as required.
 *  Set up the ICU callback function.
 *  Set the direction for the trigger pin as output through the GPIO driver.
 *  Inputs: None.
 *  Return: None.
 * */
void Ultrasonic_init(void);

/*description:
 * Send the trigger pulse to the ultrasonic sensor.
 * Send Inputs: None.
 * Send Return: None.
 * */
void Ultrasonic_Trigger(void);

/*description:
 *  Send the trigger pulse by using the Ultrasonic_Trigger function.
 *  Start the measurement process via the ICU driver.
 *  Inputs: None.
 *  Return: The measured distance in centimeters.
 * */
uint16 Ultrasonic_readDistance(void);

/*description:
 *  This is the callback function called by the ICU driver.
 *  It calculates the high time (pulse time) generated by the ultrasonic sensor.
 *  Inputs: None.
 *  Return: None.
 * */
void Ultrasonic_edgeProcessing(void);


/*this disables the ultrasonic by disabling the icu
 * */
void Ultrasonic_deint();

#endif /* ULTRASONIC_SENSOR_H_ */
