/*
 * ultrasonic_sensor.c
 *
 *  Created on: Oct 2, 2025
 *      Author: Abdullah Said
 */

#include "ultrasonic_sensor.h"
#include "gpio.h"
#include "icu.h"
#include "util/delay.h"


/*to what is the next event in order to setup the icu in the different cases
 * */
uint8 g_edgeCount = 0;

/*to calculate the time taken for the raising edge
 * */
uint16 g_timeHigh = 0;

/*description:
 *  Initialize the ICU driver as required.
 *  Set up the ICU callback function.
 *  Set the direction for the trigger pin as output through the GPIO driver.
 *  Inputs: None.
 *  Return: None.
 * */
void Ultrasonic_init(void) {
	/*Initialize the ICU driver as required.
	 * */

	ICU_ConfigType ICU_Configuration = { F_CPU_8, RAISING };
	ICU_init(&ICU_Configuration);


	/*Set up the ICU callback function.
	 * */
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/*set the direction for the trigger pin as output through the GPIO driver.
	 * */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID,
			ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);

}

/*description:
 * Send the trigger pulse to the ultrasonic sensor.
 * Send Inputs: None.
 * Send Return: None.
 * */
void Ultrasonic_Trigger(void) {

	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID,
			LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID,
			LOGIC_LOW);

}

/*description:
 *  Send the trigger pulse by using the Ultrasonic_Trigger function.
 *  Start the measurement process via the ICU driver.
 *  Inputs: None.
 *  Return: The measured distance in centimeters.
 * */
uint16 Ultrasonic_readDistance(void) {

	Ultrasonic_Trigger();

	uint16 distance = (( g_timeHigh)*2 / 117.6);

	return distance;
}

/*description:
 *  This is the callback function called by the ICU driver.
 *  It calculates the high time (pulse time) generated by the ultrasonic sensor.
 *  Inputs: None.
 *  Return: None.
 * */
void Ultrasonic_edgeProcessing(void) {
	/*this is the function that will happen in the isr
	 * first, it increments the counter
	 * then checks its value
	 * */
	g_edgeCount++;
	if (g_edgeCount == 1) {
		/*this means that the high interval starts
		 * so, we clear the timer counter and then detect the falling edge
		 * and this will represent that the high interval ends
		 * */
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(FALLING);
	} else if (g_edgeCount == 2) {
		/*this means that the high interval ends so we will save the value
		 * then set the icu to the raising edge as it waits the next high interval
		 * and then clear the edge counter to make it repeat its function in the next time
		 * */
		g_timeHigh = ICU_getInputCaptureValue();
		ICU_setEdgeDetectionType(RAISING);
		g_edgeCount = 0;
	}
}
/*this disables the ultrasonic by disabling the icu
 * */
void Ultrasonic_deint(){
	ICU_deInit();
}
